# System utilities
SYSTEM_UTILS=(
  htop
  1password
  1password-blur-me-not
  lazygit
  lazydocker
  stow
  fzf
  zip
  unzip
  wget
  curl
  ripgrep
  github-cli
  thefuck
  jq
  yq
  uwsm
  zoxide
  regreet
  cliphist
)

# Development tools
DEV_TOOLS=(
  vim
  bat
  zsh
  neovim
  tmux
  ghostty
  ghostty-terminfo
  ghostty-shell-integration
  go
)

# System maintenance
MAINTENANCE=(
  snapper
  btrfs-assistant
  snap-pac
  grub-btrfs
  snap-pac-grub
)

# Desktop environment
DESKTOP=(
  hyprpaper
  wayland
  nautilus
  gnome-tweaks
  nordic-wallpapers
  nwg-look
)

# Media packages
MEDIA=(
  vlc
)

# Fonts
FONTS=(
  ttf-jetbrains-mono
  ttf-jetbrains-mono-nerd
  adwaita-fonts
  adwaita-icon-theme
  adwaita-cursors
  noto-fonts
  noto-fonts-emoji
)

# Services to enable
SERVICES=(
  # NetworkManager.service
)
